port: 3000
redis:
  url: redis://localhost:6379/0
  addr: "127.0.0.1:6379"
jwt:
  secret: devsecret
  issuer: horizon-auth
db:
  host: localhost
  name: horizon
  password: postgres
  port: 5432
  timezone: Europe/Istanbul
  user: postgres
env: dev
email:
  name: Horizon
  from: noreply@gethorizon.com
smtp:
  identity: ""
  username: ""
  password: ""
  addr: "localhost:2500"
  host: localhost
minio:
  user: ROOTNAME
  password: CHANGEME123
  endpoint: "localhost:9000"
  buckets:
    default: default-bucket
    profile-images: profile-images-bucket
  location: eu-central-1
api:
  logger:
    type: file
  auth:
    token:
      access-ttl: 480
      refresh-ttl: 20160
    password:
      min-security: 2
      reset-url: "http://localhost:5173/password/reset/%s?email=%s"
    email:
      verify-url: "http://localhost:5173/verify-email/%s?email=%s"
    send-login-alert-email: true
  geo:
    ip2locationdb: "iplocation.BIN"
    geocode: "geocode.json"
cron:
  category-service-count: "*/10 * * * *"
