port: 3000
redis:
  url: redis://localhost:6379/0
  addr: "127.0.0.1:6379"
jwt:
  secret: devsecret
  issuer: horizon-auth
db:
  host: localhost
  name: horizon
  password: postgres
  port: 5432
  timezone: Europe/Istanbul
  user: postgres
env: dev
email:
  name: Horizon
smtp:
  addr: smtp.gmail.com:587
  host: smtp.gmail.com
api:
  logger:
    format: "time=${time_rfc3339}, method=${method}, uri=${uri}, status=${status}, error=${error}, latency=${latency_human}\n"
  auth:
    password:
      min-security: 2
      reset-url: "http://localhost:5173/password/reset/%s"
    email:
      verify-url: "http://localhost:5173/verify-email/%s"
