package config

const (
	MINIO_ENDPOINT           = "minio.endpoint"
	MINIO_USER               = "minio.user"
	MINIO_PASSWORD           = "minio.password"
	MINIO_BUCKETS            = "minio.buckets"
	MINIO_LOCATION           = "minio.location"
	MINIO_AUTOCREATE_BUCKETS = "minio.autocreate-buckets"
	API_LOGGER_TYPE          = "api.logger.type"
	PORT                     = "port"
	ENV                      = "env"
	DB_HOST                  = "db.host"
	DB_NAME                  = "db.name"
	DB_USER                  = "db.user"
	DB_PASSWORD              = "db.password"
	DB_PORT                  = "db.port"
	DB_TIMEZONE              = "db.timezone"
	GOOGLE_CLIENT_ID         = "api.auth.google.client-id"
	GOOGLE_CLIENT_SECRET     = "api.auth.google.client-secret"
	GOOGLE_CALLBACK          = "api.auth.google.callback"
	GITHUB_CLIENT_ID         = "api.auth.github.client-id"
	GITHUB_CLIENT_SECRET     = "api.auth.github.client-secret"
	GITHUB_CALLBACK          = "api.auth.github.callback"
	AUTH_SIGN_KEY            = "api.auth.sign-key"
)
