// Package swaggerdocs Code generated by swaggo/swag. DO NOT EDIT
package swaggerdocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://localhost:3000/terms",
        "contact": {
            "name": "Mert Turkmenoglu",
            "url": "https://mertturkmenoglu.com",
            "email": "gethorizonapp@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://mit-license.org/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/aggregations/home": {
            "get": {
                "description": "An endpoint to fetch multiple homepage queries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aggregations"
                ],
                "summary": "Fetch multiple homepage entities in a single request",
                "responses": {
                    "200": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/GetHomeAggregationsResponseDto"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/auth/credentials/login": {
            "post": {
                "description": "Logs in the user with email and password",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login with email and password",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AuthLoginRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Invalid email or password",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/credentials/register": {
            "post": {
                "description": "Registers a new user with email and password",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register with email and password",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AuthRegisterRequestDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Invalid email or username",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/forgot-password/reset": {
            "post": {
                "description": "Resets the password of the user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Reset password",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AuthResetPasswordRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Invalid email or code",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/forgot-password/send": {
            "post": {
                "description": "Sends a forgot password email to the user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Send forgot password email",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AuthSendForgotPasswordEmailRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Invalid email",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/google": {
            "get": {
                "description": "Login with Google OAuth2",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login with Google OAuth2",
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/google/callback": {
            "get": {
                "description": "Google OAuth2 callback",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Google OAuth2 callback",
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Logs out the current user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logs out the current user",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Gets the currently authenticated user or returns an error",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Gets the current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/AuthGetMeResponseDto"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/verify-email/send": {
            "post": {
                "description": "Sends a verification email to the user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Send verification email",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AuthSendVerificationEmailRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Invalid email or email already verified",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/verify-email/verify": {
            "get": {
                "description": "Verifies the email of the user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Invalid or expired verification code",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/bookmarks": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Gets all bookmarks for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookmarks"
                ],
                "summary": "Get bookmarks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HPR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/BookmarksBookmarksResponseDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new bookmark with the given HService ID for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookmarks"
                ],
                "summary": "Create a new bookmark",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/BookmarksCreateBookmarkRequestDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/BookmarksCreateBookmarkResponseDto"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/bookmarks/{hservice_id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Checks if a bookmark exists for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bookmarks"
                ],
                "summary": "Check if a bookmark exists",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HService ID",
                        "name": "hservice_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes a bookmark with the given HService ID for the current user",
                "tags": [
                    "Bookmarks"
                ],
                "summary": "Delete a bookmark",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HService ID",
                        "name": "hservice_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/favorites": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Gets all favorites for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favorites"
                ],
                "summary": "Get favorites",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HPR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/FavoritesFavoritesResponseDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new favorite with the given HService ID for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favorites"
                ],
                "summary": "Create a new favorite",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/FavoritesCreateFavoriteRequestDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/FavoritesCreateFavoriteResponseDto"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/favorites/username/{username}": {
            "get": {
                "description": "Gets all favorites for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favorites"
                ],
                "summary": "Get favorites by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HPR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/FavoritesFavoritesResponseDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/favorites/{hservice_id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Checks if a favorite exists for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Favorites"
                ],
                "summary": "Check if a favorite exists",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HService ID",
                        "name": "hservice_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes a favorite with the given HService ID for the current user",
                "tags": [
                    "Favorites"
                ],
                "summary": "Delete a favorite",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HService ID",
                        "name": "hservice_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/health/": {
            "get": {
                "description": "An endpoint to be used by load balancers to check the health of the service.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/HealthGetHealthResponseDto"
                        }
                    }
                }
            }
        },
        "/hservices": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Gets all hservices for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HServices"
                ],
                "summary": "Get my hservices",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HPR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/HServicesHServiceWithoutUserResponseDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new hservice with the given title for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HServices"
                ],
                "summary": "Create a new hservice",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/HServicesCreateHServiceRequestDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/HServicesHServiceWithoutUserResponseDto"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/hservices/user/{username}": {
            "get": {
                "description": "Gets all hservices for the given username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HServices"
                ],
                "summary": "Get hservices by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HPR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/HServicesHServiceResponseDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/hservices/{id}": {
            "get": {
                "description": "Gets a hservice with the given ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HServices"
                ],
                "summary": "Get hservice by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HService ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HMR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/HServicesHServiceResponseDto"
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/HServicesHServiceMetadataDto"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/uploads/new-url": {
            "get": {
                "description": "Gets a new upload URL for the given type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uploads"
                ],
                "summary": "Get new upload URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type of upload",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 5,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Number of files to be uploaded",
                        "name": "count",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Mime type of the files to be uploaded",
                        "name": "mime",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HR"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/UploadsUploadObj"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AggregationsHServiceResponseDto": {
            "description": "Basic service information with user information",
            "type": "object",
            "required": [
                "category",
                "createdAt",
                "deliveryTime",
                "deliveryTimespan",
                "description",
                "id",
                "isOnline",
                "location",
                "media",
                "price",
                "priceTimespan",
                "priceUnit",
                "slug",
                "title",
                "totalPoints",
                "totalVotes",
                "updatedAt",
                "user",
                "userId"
            ],
            "properties": {
                "category": {
                    "type": "integer",
                    "example": 1
                },
                "createdAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "deliveryTime": {
                    "type": "integer",
                    "example": 1
                },
                "deliveryTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "description": {
                    "type": "string",
                    "example": "Example service description"
                },
                "id": {
                    "type": "string",
                    "example": "7234882566245847040"
                },
                "isOnline": {
                    "type": "boolean",
                    "example": true
                },
                "location": {
                    "type": "string",
                    "example": "Example Location"
                },
                "media": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "price": {
                    "type": "number",
                    "example": 10
                },
                "priceTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "priceUnit": {
                    "type": "string",
                    "example": "USD"
                },
                "slug": {
                    "type": "string",
                    "example": "example-service"
                },
                "title": {
                    "type": "string",
                    "example": "Example Service"
                },
                "totalPoints": {
                    "type": "integer",
                    "example": 50
                },
                "totalVotes": {
                    "type": "integer",
                    "example": 10
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                },
                "user": {
                    "$ref": "#/definitions/AggregationsUserResponseDto"
                },
                "userId": {
                    "type": "string",
                    "example": "528696135489945615"
                }
            }
        },
        "AggregationsUserResponseDto": {
            "description": "Basic user information",
            "type": "object",
            "required": [
                "createdAt",
                "fullName",
                "id",
                "username"
            ],
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "id": {
                    "type": "string",
                    "example": "528696135489945615"
                },
                "profileImage": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "AuthGetMeResponseDto": {
            "type": "object",
            "required": [
                "createdAt",
                "email",
                "fullName",
                "id",
                "isActive",
                "isEmailVerified",
                "lastLogin",
                "role",
                "updatedAt",
                "username"
            ],
            "properties": {
                "createdAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "googleId": {
                    "type": "string",
                    "example": "10887502189381205719451"
                },
                "id": {
                    "type": "string",
                    "example": "528696135489945615"
                },
                "isActive": {
                    "type": "boolean",
                    "example": true
                },
                "isEmailVerified": {
                    "type": "boolean",
                    "example": true
                },
                "lastLogin": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "profileImage": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "role": {
                    "type": "string",
                    "example": "user"
                },
                "updatedAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "AuthLoginRequestDto": {
            "description": "Login request dto",
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "maxLength": 128,
                    "minLength": 6,
                    "example": "password123"
                }
            }
        },
        "AuthRegisterRequestDto": {
            "type": "object",
            "required": [
                "email",
                "fullName",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 3,
                    "example": "johndoe@example.com"
                },
                "fullName": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 3,
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "maxLength": 128,
                    "minLength": 6,
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 4,
                    "example": "johndoe"
                }
            }
        },
        "AuthResetPasswordRequestDto": {
            "type": "object",
            "required": [
                "code",
                "email",
                "newPassword"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                },
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "newPassword": {
                    "type": "string",
                    "format": "password",
                    "maxLength": 128,
                    "minLength": 6,
                    "example": "password123"
                }
            }
        },
        "AuthSendForgotPasswordEmailRequestDto": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                }
            }
        },
        "AuthSendVerificationEmailRequestDto": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                }
            }
        },
        "BookmarksBookmarksResponseDto": {
            "description": "Basic bookmark information",
            "type": "object",
            "required": [
                "createdAt",
                "hservice",
                "hserviceId",
                "id",
                "userId"
            ],
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "hservice": {
                    "$ref": "#/definitions/BookmarksHServiceDto"
                },
                "hserviceId": {
                    "type": "string",
                    "example": "7235190573525635072"
                },
                "id": {
                    "type": "string",
                    "example": "7235190573525635072"
                },
                "userId": {
                    "type": "string",
                    "example": "528696135489945615"
                }
            }
        },
        "BookmarksCreateBookmarkRequestDto": {
            "description": "CreateBookmarkRequestDto",
            "type": "object",
            "required": [
                "hserviceId"
            ],
            "properties": {
                "hserviceId": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1,
                    "example": "7235190573525635072"
                }
            }
        },
        "BookmarksCreateBookmarkResponseDto": {
            "description": "CreateBookmarkResponseDto",
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "7235190573525635072"
                }
            }
        },
        "BookmarksHServiceDto": {
            "description": "Basic service information without user information",
            "type": "object",
            "required": [
                "category",
                "createdAt",
                "deliveryTime",
                "deliveryTimespan",
                "description",
                "id",
                "isOnline",
                "location",
                "media",
                "price",
                "priceTimespan",
                "priceUnit",
                "slug",
                "title",
                "totalPoints",
                "totalVotes",
                "updatedAt",
                "userId"
            ],
            "properties": {
                "category": {
                    "type": "integer",
                    "example": 1
                },
                "createdAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "deliveryTime": {
                    "type": "integer",
                    "example": 1
                },
                "deliveryTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "description": {
                    "type": "string",
                    "example": "Example service description"
                },
                "id": {
                    "type": "string",
                    "example": "7235190573525635072"
                },
                "isOnline": {
                    "type": "boolean",
                    "example": true
                },
                "location": {
                    "type": "string",
                    "example": "Example Location"
                },
                "media": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "price": {
                    "type": "number",
                    "example": 10
                },
                "priceTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "priceUnit": {
                    "type": "string",
                    "example": "USD"
                },
                "slug": {
                    "type": "string",
                    "example": "example-service"
                },
                "title": {
                    "type": "string",
                    "example": "Example Service"
                },
                "totalPoints": {
                    "type": "integer",
                    "example": 50
                },
                "totalVotes": {
                    "type": "integer",
                    "example": 10
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                },
                "userId": {
                    "type": "string",
                    "example": "528696135489945615"
                }
            }
        },
        "FavoritesCreateFavoriteRequestDto": {
            "description": "CreateFavoriteRequestDto",
            "type": "object",
            "required": [
                "hserviceId"
            ],
            "properties": {
                "hserviceId": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1,
                    "example": "7235190573525635072"
                }
            }
        },
        "FavoritesCreateFavoriteResponseDto": {
            "description": "CreateFavoriteResponseDto",
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "7235190573525635072"
                }
            }
        },
        "FavoritesFavoritesResponseDto": {
            "description": "Basic favorite information",
            "type": "object",
            "required": [
                "createdAt",
                "hservice",
                "hserviceId",
                "id",
                "userId"
            ],
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "hservice": {
                    "$ref": "#/definitions/FavoritesHServiceDto"
                },
                "hserviceId": {
                    "type": "string",
                    "example": "7235190573525635072"
                },
                "id": {
                    "type": "string",
                    "example": "7235190573525635072"
                },
                "userId": {
                    "type": "string",
                    "example": "528696135489945615"
                }
            }
        },
        "FavoritesHServiceDto": {
            "description": "Basic service information without user information",
            "type": "object",
            "required": [
                "category",
                "createdAt",
                "deliveryTime",
                "deliveryTimespan",
                "description",
                "id",
                "isOnline",
                "location",
                "media",
                "price",
                "priceTimespan",
                "priceUnit",
                "slug",
                "title",
                "totalPoints",
                "totalVotes",
                "updatedAt",
                "userId"
            ],
            "properties": {
                "category": {
                    "type": "integer",
                    "example": 1
                },
                "createdAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "deliveryTime": {
                    "type": "integer",
                    "example": 1
                },
                "deliveryTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "description": {
                    "type": "string",
                    "example": "Example service description"
                },
                "id": {
                    "type": "string",
                    "example": "7235190573525635072"
                },
                "isOnline": {
                    "type": "boolean",
                    "example": true
                },
                "location": {
                    "type": "string",
                    "example": "Example Location"
                },
                "media": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "price": {
                    "type": "number",
                    "example": 10
                },
                "priceTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "priceUnit": {
                    "type": "string",
                    "example": "USD"
                },
                "slug": {
                    "type": "string",
                    "example": "example-service"
                },
                "title": {
                    "type": "string",
                    "example": "Example Service"
                },
                "totalPoints": {
                    "type": "integer",
                    "example": 50
                },
                "totalVotes": {
                    "type": "integer",
                    "example": 10
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                },
                "userId": {
                    "type": "string",
                    "example": "528696135489945615"
                }
            }
        },
        "GetHomeAggregationsResponseDto": {
            "description": "Response for home aggregations",
            "type": "object",
            "required": [
                "favorites",
                "featured",
                "new",
                "popular"
            ],
            "properties": {
                "favorites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AggregationsHServiceResponseDto"
                    }
                },
                "featured": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AggregationsHServiceResponseDto"
                    }
                },
                "new": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AggregationsHServiceResponseDto"
                    }
                },
                "popular": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AggregationsHServiceResponseDto"
                    }
                }
            }
        },
        "HMR": {
            "description": "Metadata Response",
            "type": "object",
            "required": [
                "data",
                "metadata"
            ],
            "properties": {
                "data": {},
                "metadata": {}
            }
        },
        "HPR": {
            "description": "Paginated Response",
            "type": "object",
            "required": [
                "data",
                "pagination"
            ],
            "properties": {
                "data": {},
                "pagination": {
                    "$ref": "#/definitions/pagination.Pagination"
                }
            }
        },
        "HR": {
            "description": "Response",
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {}
            }
        },
        "HServicesCreateHServiceRequestDto": {
            "description": "CreateHServiceRequestDto",
            "type": "object",
            "required": [
                "category",
                "deliveryTime",
                "deliveryTimespan",
                "description",
                "isOnline",
                "location",
                "media",
                "price",
                "priceTimespan",
                "priceUnit",
                "title"
            ],
            "properties": {
                "category": {
                    "type": "integer",
                    "maximum": 32,
                    "minimum": 1,
                    "example": 1
                },
                "deliveryTime": {
                    "type": "integer",
                    "maximum": 32,
                    "minimum": 1,
                    "example": 1
                },
                "deliveryTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "description": {
                    "type": "string",
                    "maxLength": 4096,
                    "minLength": 5,
                    "example": "Example service description"
                },
                "isOnline": {
                    "type": "boolean",
                    "example": true
                },
                "location": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 1,
                    "example": "Example Location"
                },
                "media": {
                    "type": "string"
                },
                "price": {
                    "type": "number",
                    "maximum": 10000,
                    "minimum": 1,
                    "example": 10
                },
                "priceTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "priceUnit": {
                    "type": "string",
                    "example": "USD"
                },
                "title": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 5,
                    "example": "Example Service"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "HServicesHServiceMetadataDto": {
            "description": "HServiceMetadataDto",
            "type": "object",
            "required": [
                "isBookmarked",
                "isFavorite"
            ],
            "properties": {
                "isBookmarked": {
                    "type": "boolean",
                    "example": true
                },
                "isFavorite": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "HServicesHServiceResponseDto": {
            "description": "Basic service information with user information",
            "type": "object",
            "required": [
                "category",
                "createdAt",
                "deliveryTime",
                "deliveryTimespan",
                "description",
                "id",
                "isOnline",
                "location",
                "media",
                "price",
                "priceTimespan",
                "priceUnit",
                "slug",
                "title",
                "totalPoints",
                "totalVotes",
                "updatedAt",
                "user",
                "userId"
            ],
            "properties": {
                "category": {
                    "type": "integer",
                    "example": 1
                },
                "createdAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "deliveryTime": {
                    "type": "integer",
                    "example": 1
                },
                "deliveryTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "description": {
                    "type": "string",
                    "example": "Example service description"
                },
                "id": {
                    "type": "string",
                    "example": "7234882566245847040"
                },
                "isOnline": {
                    "type": "boolean",
                    "example": true
                },
                "location": {
                    "type": "string",
                    "example": "Example Location"
                },
                "media": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "price": {
                    "type": "number",
                    "example": 10
                },
                "priceTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "priceUnit": {
                    "type": "string",
                    "example": "USD"
                },
                "slug": {
                    "type": "string",
                    "example": "example-service"
                },
                "title": {
                    "type": "string",
                    "example": "Example Service"
                },
                "totalPoints": {
                    "type": "integer",
                    "example": 50
                },
                "totalVotes": {
                    "type": "integer",
                    "example": 10
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                },
                "user": {
                    "$ref": "#/definitions/HServicesUserResponseDto"
                },
                "userId": {
                    "type": "string",
                    "example": "528696135489945615"
                }
            }
        },
        "HServicesHServiceWithoutUserResponseDto": {
            "description": "Basic service information without user information",
            "type": "object",
            "required": [
                "category",
                "createdAt",
                "deliveryTime",
                "deliveryTimespan",
                "description",
                "id",
                "isOnline",
                "location",
                "media",
                "price",
                "priceTimespan",
                "priceUnit",
                "slug",
                "title",
                "totalPoints",
                "totalVotes",
                "updatedAt",
                "userId"
            ],
            "properties": {
                "category": {
                    "type": "integer",
                    "example": 1
                },
                "createdAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "deliveryTime": {
                    "type": "integer",
                    "example": 1
                },
                "deliveryTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "description": {
                    "type": "string",
                    "example": "Example service description"
                },
                "id": {
                    "type": "string",
                    "example": "7234882566245847040"
                },
                "isOnline": {
                    "type": "boolean",
                    "example": true
                },
                "location": {
                    "type": "string",
                    "example": "Example Location"
                },
                "media": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "price": {
                    "type": "number",
                    "example": 10
                },
                "priceTimespan": {
                    "type": "string",
                    "example": "HOURLY"
                },
                "priceUnit": {
                    "type": "string",
                    "example": "USD"
                },
                "slug": {
                    "type": "string",
                    "example": "example-service"
                },
                "title": {
                    "type": "string",
                    "example": "Example Service"
                },
                "totalPoints": {
                    "type": "integer",
                    "example": 50
                },
                "totalVotes": {
                    "type": "integer",
                    "example": 10
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                },
                "userId": {
                    "type": "string",
                    "example": "528696135489945615"
                }
            }
        },
        "HServicesUserResponseDto": {
            "description": "Basic user information",
            "type": "object",
            "required": [
                "createdAt",
                "fullName",
                "id",
                "username"
            ],
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2024-08-26T10:24:13.508676+03:00"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "id": {
                    "type": "string",
                    "example": "528696135489945615"
                },
                "profileImage": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "HealthGetHealthResponseDto": {
            "description": "GetHealthResponseDto",
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "UploadsUploadObj": {
            "description": "UploadObj",
            "type": "object",
            "required": [
                "key",
                "url"
            ],
            "properties": {
                "key": {
                    "type": "string",
                    "example": "a690dd36-6a90-465f-81d5-bf0a03be084c"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                }
            }
        },
        "echo.HTTPError": {
            "type": "object",
            "properties": {
                "message": {}
            }
        },
        "pagination.Pagination": {
            "type": "object",
            "properties": {
                "hasNext": {
                    "type": "boolean"
                },
                "hasPrevious": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                },
                "totalRecords": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "description": "Cookie based session authentication",
            "type": "apiKey",
            "name": "__horizon_auth",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Horizon API",
	Description:      "Horizon backend services",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
