// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	Email                string
	PasswordHash         pgtype.Text
	GoogleID             pgtype.Text
	IsEmailVerified      pgtype.Bool
	IsActive             pgtype.Bool
	Role                 pgtype.Text
	LastLogin            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	PasswordResetToken   pgtype.Text
	PasswordResetExpires pgtype.Timestamptz
	LoginAttempts        pgtype.Int4
	LockoutUntil         pgtype.Timestamptz
}

type Author struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}

type User struct {
	ID           pgtype.UUID
	FullName     string
	Username     string
	Gender       pgtype.Text
	ProfileImage pgtype.Text
}
