// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Priceunit string

const (
	PriceunitUSD Priceunit = "USD"
	PriceunitEUR Priceunit = "EUR"
	PriceunitJPY Priceunit = "JPY"
	PriceunitGBP Priceunit = "GBP"
	PriceunitAUD Priceunit = "AUD"
	PriceunitCAD Priceunit = "CAD"
	PriceunitCHF Priceunit = "CHF"
	PriceunitINR Priceunit = "INR"
	PriceunitBRL Priceunit = "BRL"
	PriceunitCZK Priceunit = "CZK"
	PriceunitTRY Priceunit = "TRY"
)

func (e *Priceunit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Priceunit(s)
	case string:
		*e = Priceunit(s)
	default:
		return fmt.Errorf("unsupported scan type for Priceunit: %T", src)
	}
	return nil
}

type NullPriceunit struct {
	Priceunit Priceunit
	Valid     bool // Valid is true if Priceunit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriceunit) Scan(value interface{}) error {
	if value == nil {
		ns.Priceunit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Priceunit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriceunit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Priceunit), nil
}

type Reportstatus string

const (
	ReportstatusPending    Reportstatus = "pending"
	ReportstatusInProgress Reportstatus = "in_progress"
	ReportstatusDone       Reportstatus = "done"
)

func (e *Reportstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Reportstatus(s)
	case string:
		*e = Reportstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Reportstatus: %T", src)
	}
	return nil
}

type NullReportstatus struct {
	Reportstatus Reportstatus
	Valid        bool // Valid is true if Reportstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Reportstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Reportstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Reportstatus), nil
}

type Reporttargettype string

const (
	ReporttargettypeHservice Reporttargettype = "hservice"
	ReporttargettypeUser     Reporttargettype = "user"
	ReporttargettypeList     Reporttargettype = "list"
	ReporttargettypeReview   Reporttargettype = "review"
)

func (e *Reporttargettype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Reporttargettype(s)
	case string:
		*e = Reporttargettype(s)
	default:
		return fmt.Errorf("unsupported scan type for Reporttargettype: %T", src)
	}
	return nil
}

type NullReporttargettype struct {
	Reporttargettype Reporttargettype
	Valid            bool // Valid is true if Reporttargettype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReporttargettype) Scan(value interface{}) error {
	if value == nil {
		ns.Reporttargettype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Reporttargettype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReporttargettype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Reporttargettype), nil
}

type Reviewvotetype string

const (
	ReviewvotetypeLIKE    Reviewvotetype = "LIKE"
	ReviewvotetypeDISLIKE Reviewvotetype = "DISLIKE"
)

func (e *Reviewvotetype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Reviewvotetype(s)
	case string:
		*e = Reviewvotetype(s)
	default:
		return fmt.Errorf("unsupported scan type for Reviewvotetype: %T", src)
	}
	return nil
}

type NullReviewvotetype struct {
	Reviewvotetype Reviewvotetype
	Valid          bool // Valid is true if Reviewvotetype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewvotetype) Scan(value interface{}) error {
	if value == nil {
		ns.Reviewvotetype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Reviewvotetype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewvotetype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Reviewvotetype), nil
}

type Worktimespan string

const (
	WorktimespanHOURLY  Worktimespan = "HOURLY"
	WorktimespanDAILY   Worktimespan = "DAILY"
	WorktimespanWEEKLY  Worktimespan = "WEEKLY"
	WorktimespanMONTHLY Worktimespan = "MONTHLY"
	WorktimespanYEARLY  Worktimespan = "YEARLY"
)

func (e *Worktimespan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Worktimespan(s)
	case string:
		*e = Worktimespan(s)
	default:
		return fmt.Errorf("unsupported scan type for Worktimespan: %T", src)
	}
	return nil
}

type NullWorktimespan struct {
	Worktimespan Worktimespan
	Valid        bool // Valid is true if Worktimespan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorktimespan) Scan(value interface{}) error {
	if value == nil {
		ns.Worktimespan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Worktimespan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorktimespan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Worktimespan), nil
}

type Admin struct {
	UserID    string
	CreatedBy pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Bookmark struct {
	ID         pgtype.UUID
	UserID     string
	HserviceID string
	CreatedAt  pgtype.Timestamptz
}

type Country struct {
	ID             int32
	Name           string
	Iso2           string
	NumericCode    string
	PhoneCode      string
	Capital        string
	Currency       string
	CurrencyName   string
	CurrencySymbol string
	Tld            string
	Native         string
	Region         string
	Subregion      string
	Timezones      string
	Latitude       float64
	Longitude      float64
}

type Favorite struct {
	ID         pgtype.UUID
	UserID     string
	HserviceID string
	CreatedAt  pgtype.Timestamptz
}

type Hservice struct {
	ID               string
	UserID           string
	Title            string
	Slug             string
	Description      string
	Category         int32
	Price            float64
	PriceUnit        Priceunit
	PriceTimespan    Worktimespan
	IsOnline         bool
	Url              pgtype.Text
	Location         string
	DeliveryTime     int32
	DeliveryTimespan Worktimespan
	TotalPoints      int64
	TotalVotes       int32
	Media            []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type List struct {
	ID        string
	Title     string
	UserID    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ListItem struct {
	ID         string
	ListID     string
	HserviceID string
	ItemOrder  int32
}

type Report struct {
	ID              string
	ReporterID      string
	TargetID        string
	TargetType      Reporttargettype
	Reason          string
	Comment         pgtype.Text
	ReportStatus    Reportstatus
	AssigneeID      pgtype.Text
	AssigneeComment pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Review struct {
	ID           string
	UserID       string
	HserviceID   string
	Rating       int16
	Comment      string
	Media        []byte
	LikeCount    int32
	DislikeCount int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ReviewsVote struct {
	ID        string
	UserID    string
	ReviewID  string
	VoteType  Reviewvotetype
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID          string
	UserID      string
	SessionData pgtype.Text
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type State struct {
	ID          int32
	Name        string
	CountryID   int32
	CountryCode string
	CountryName string
	StateCode   string
	Type        pgtype.Text
	Latitude    float64
	Longitude   float64
}

type User struct {
	ID                   string
	Email                string
	Username             string
	FullName             string
	PasswordHash         pgtype.Text
	GoogleID             pgtype.Text
	IsEmailVerified      bool
	IsActive             bool
	Role                 string
	PasswordResetToken   pgtype.Text
	PasswordResetExpires pgtype.Timestamptz
	LoginAttempts        pgtype.Int4
	LockoutUntil         pgtype.Timestamptz
	Gender               pgtype.Text
	ProfileImage         pgtype.Text
	LastLogin            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}
