name: horizon

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: horizon

  minio:
    ports:
      - 9000:9000
      - 9001:9001
    container_name: minio
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=horizondev
      - MINIO_ROOT_PASSWORD=horizondev
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"

  keycloak:
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=horizon
      - KEYCLOAK_ADMIN_PASSWORD=horizon
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev
