name: horizon

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: horizon

  minio:
    ports:
      - 9000:9000
      - 9001:9001
    container_name: minio
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=horizondev
      - MINIO_ROOT_PASSWORD=horizondev
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"

  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: "--data-dir /data --api-key=horizon --enable-cors"

  typesense-dashboard:
    restart: always
    ports:
      - 3006:80
    image: ghcr.io/bfritscher/typesense-dashboard:latest
