services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - redisnet
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: horizon

networks:
  redisnet:
