name: horizon
services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - redisnet
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: horizon
  asynqmon:
    image: hibiken/asynqmon
    networks:
      - redisnet
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
  minio:
    ports:
        - 9000:9000
        - 9001:9001
    container_name: minio
    volumes:
        - ~/minio/data:/data
    environment:
        - MINIO_ROOT_USER=ROOTNAME
        - MINIO_ROOT_PASSWORD=CHANGEME123
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"

networks:
  redisnet:
